import React from "react";
import ContactUS from "../../components/ContactUs/ContactUS";

export const metadata = {
  title: "Contact Us - SwiftSupport",
  description: "Generated by SwiftSupport",
  openGraph: {
    title: "Contact Us - SwiftSupport",
    description: "Generated by SwiftSupport",
    url: process.env.NEXT_PUBLIC_BASE_URL,
    siteName: "SwiftSupport",
    locale: "en-US",
    type: "website",
  },
  twitter: {
    title: "Contact Us - SwiftSupport",
    description: "Generated by SwiftSupport",
    card: "summary_large_image",
  },
  alternates: {
    canonical: process.env.NEXT_PUBLIC_BASE_URL,
  },
};

const page = () => {
  return (
    <div className="bg_contactus">
      <ContactUS />
    </div>
  );
};

export default page;
