import React from "react";
import PrivacyPolicy from "@/app/components/PrivacyPolicy";

export const metadata = {
  title: "Privacy Policy - SwiftSupport",
  description: "Generated by SwiftSupport",
  openGraph: {
    title: "Privacy Policy - SwiftSupport",
    description: "Generated by SwiftSupport",
    url: process.env.NEXT_PUBLIC_BASE_URL,
    siteName: "SwiftSupport",
    locale: "en-US",
    type: "website",
  },
  twitter: {
    title: "Privacy Policy - SwiftSupport",
    description: "Generated by SwiftSupport",
    card: "summary_large_image",
  },
  alternates: {
    canonical: process.env.NEXT_PUBLIC_BASE_URL,
  },
};

const page = () => {
  return <PrivacyPolicy />;
};

export default page;
