import dynamic from "next/dynamic";
import "./globals.css";

const Header = dynamic(() => import("./components/Header"));
const Footer = dynamic(() => import("./components/Footer"));

export const metadata = {
  title: "SwiftSupport",
  description: "Generated by SwiftSupport",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Header />
      <body>{children}</body>
      <Footer />
    </html>
  );
}
