import HomePage from "./(pages)/home/page";

export const metadata = {
  title: "SwiftSupport",
  description: "Generated by SwiftSupport",
  openGraph: {
    title: "SwiftSupport",
    description: "Generated by SwiftSupport",
    url: process.env.NEXT_PUBLIC_BASE_URL,
    siteName: "SwiftSupport",
    locale: "en-US",
    type: "website",
  },
  twitter: {
    title: "SwiftSupport",
    description: "Generated by SwiftSupport",
    card: "summary_large_image",
  },
  alternates: {
    canonical: process.env.NEXT_PUBLIC_BASE_URL,
  },
};
export default function Home() {
  return <HomePage />;
}
