import TermsAndConditions from "@/app/components/TermsAndConditions";
import React from "react";

export const metadata = {
  title: "Terms and Conditions - SwiftSupport",
  description: "Generated by SwiftSupport",
  openGraph: {
    title: "Terms and Conditions - SwiftSupport",
    description: "Generated by SwiftSupport",
    url: process.env.NEXT_PUBLIC_BASE_URL,
    siteName: "SwiftSupport",
    locale: "en-US",
    type: "website",
  },
  twitter: {
    title: "Terms and Conditions - SwiftSupport",
    description: "Generated by SwiftSupport",
    card: "summary_large_image",
  },
  alternates: {
    canonical: process.env.NEXT_PUBLIC_BASE_URL,
  },
};
const page = () => {
  return <TermsAndConditions />;
};

export default page;
